### ISSUE TITLE
Not booting cm11 rc15 and Xcelerate pb 4

### ISSUE THREAD

**Issue by jabnakar** [zeroblade1984/armani_kernel#1]
[FALSE ALARM, NEEDS RC16 CM11
Description of the issue : I am not able to boot and it would show the 'miui' logo then the part where CyanogenMod animation is replaced with a 1 second black screen then the 'miui' comes up again with sometimes half of the lower screen of the display flashes purple/pinkish color.

environment and version : CM11 RC15(md5 checked), with Kernel Xcelerate Production build 4(md5 checked)
when it doesn't : Clean CM11 RC15 flash
method of reproducing the problem : Clean flashing CM11 RC15 and then flashing Kernel Xcelerate Production build 4

**Comment by zeroblade1984** [comment]
For R15 you flash build 2 or build 3 series..
