### ISSUE TITLE
CM 12.1 issue

### ISSUE THREAD

**Issue by AlvaroRosado** [zeroblade1984/armani_kernel#3]
Hi, in this game "8 Ball Poll", when is logging by google, give error and FC in R11. I have tested xcelerate R9 and works fine. I dont have more information, I hope to be helpful thank you very much for your work.

Greetings

**Comment by zeroblade1984** [comment]
send down a log as I DO NOT OWN THE DEVICE for GOD's SAKE I'm not a magician to read your minds or your phone's EMMC

/sarcasm

**Comment by AlvaroRosado** [comment]
07-02 20:40:21.252 D/FlurryAgent(17099)Starting new session
07-02 20:40:21.260 W/Settings(17099)Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
07-02 20:40:21.296 D/FlurryAgent(17099)Sending report to: http://data.flurry.com/aar.do
07-02 20:40:21.621 I/WebViewFactory(17099)Loading com.android.webview version 39 (eng.jenkins-arm) (code 399991)
07-02 20:40:21.749 I/LibraryLoader(17099)Time to load native libraries: 62 ms (timestamps 4806-4868)
07-02 20:40:21.750 I/LibraryLoader(17099)Expected native library version number "",actual native library version number ""
07-02 20:40:21.775 V/WebViewChromiumFactoryProvider(17099)Binding Chromium to main looper Looper (main, tid 1) {2d78b70c}
07-02 20:40:21.775 I/LibraryLoader(17099)Expected native library version number "",actual native library version number ""
07-02 20:40:21.801 I/chromium(17099)[INFO:library_loader_hooks.cc(104)] Chromium logging enabled: level = 0, default verbosity = 0
07-02 20:40:21.817 I/BrowserStartupController(17099)Initializing chromium process, singleProcess=true
07-02 20:40:21.827 W/art     (17099)Attempt to remove local handle scope entry from IRT, ignoring
07-02 20:40:21.915 W/AudioManagerAndroid(17099)Requires BLUETOOTH permission
07-02 20:40:21.930 W/chromium(17099)[WARNING:resource_bundle.cc(304)] locale_file_path.empty()
07-02 20:40:21.931 I/chromium(17099)[INFO:aw_browser_main_parts.cc(65)] Load from apk succesful, fd=38 off=52976 len=3763
07-02 20:40:21.980 I/chromium(17099)[INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:39 off:229484 len:1089587
07-02 20:40:22.025 I/Adreno-EGL(17099)<qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1.1.C2.05.00.00.046.002_msm8974_LA.BF.1.1.1.C2__release_AU ()
07-02 20:40:22.025 I/Adreno-EGL(17099)OpenGL ES Shader Compiler Version: E031.25.03.00
07-02 20:40:22.025 I/Adreno-EGL(17099)Build Date: 01/06/15 Tue
07-02 20:40:22.025 I/Adreno-EGL(17099)Local Branch: mybranch6793908
07-02 20:40:22.025 I/Adreno-EGL(17099)Remote Branch: quic/LA.BF.1.1.1.c2
07-02 20:40:22.025 I/Adreno-EGL(17099)Local Patches: NONE
07-02 20:40:22.025 I/Adreno-EGL(17099)Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1.1.C2.05.00.00.046.002 +  NOTHING
07-02 20:40:22.054 W/System.err(17099)java.net.UnknownHostException: Unable to resolve host "ip6.telize.com": No address associated with hostname
07-02 20:40:22.073 W/System.err(17099)at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
07-02 20:40:22.073 W/System.err(17099)at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
07-02 20:40:22.073 W/System.err(17099)at java.net.InetAddress.getAllByName(InetAddress.java:215)
07-02 20:40:22.073 W/System.err(17099)at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:29)
07-02 20:40:22.073 W/System.err(17099)at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
07-02 20:40:22.073 W/System.err(17099)at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
07-02 20:40:22.073 W/System.err(17099)at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:272)
07-02 20:40:22.073 W/System.err(17099)at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
07-02 20:40:22.073 W/System.err(17099)at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
07-02 20:40:22.073 W/System.err(17099)at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
07-02 20:40:22.073 W/System.err(17099)at com.electricsheep.asi.ag.a(Unknown Source)
07-02 20:40:22.073 W/System.err(17099)at com.electricsheep.asi.ag.doInBackground(Unknown Source)
07-02 20:40:22.073 W/System.err(17099)at android.os.AsyncTask$2.call(AsyncTask.java:292)
07-02 20:40:22.073 W/System.err(17099)at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-02 20:40:22.073 W/System.err(17099)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
07-02 20:40:22.073 W/System.err(17099)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
07-02 20:40:22.073 W/System.err(17099)at java.lang.Thread.run(Thread.java:818)
07-02 20:40:22.073 W/System.err(17099)Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
07-02 20:40:22.074 W/System.err(17099)at libcore.io.Posix.android_getaddrinfo(Native Method)
07-02 20:40:22.074 W/System.err(17099)at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
07-02 20:40:22.074 W/System.err(17099)at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
07-02 20:40:22.074 W/System.err(17099)... 16 more
07-02 20:40:22.293 W/ResourcesManager(17099)Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
07-02 20:40:22.294 W/ResourcesManager(17099)Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
07-02 20:40:22.329 I/art     (17099)Background sticky concurrent mark sweep GC freed 16802(1304KB) AllocSpace objects, 6(96KB) LOS objects, 0% free, 12MB/12MB, paused 955us total 112.958ms
07-02 20:40:22.385 I/art     (17099)Background partial concurrent mark sweep GC freed 3585(176KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 13MB/21MB, paused 9.930ms total 53.065ms
07-02 20:40:22.495 D/FlurryAgent(17099)Report successful
07-02 20:40:22.514 I/Ads     (17099)CsiReporterFactory: CSI is not enabled. No CSI reporter created.
07-02 20:40:22.591 I/Ads     (17099)Starting ad request.
07-02 20:40:22.594 I/Ads     (17099)Use AdRequest.Builder.addTestDevice("06757307983F2EE6792DD73D441580F1") to get test ads on this device.
07-02 20:40:22.616 I/Ads     (17099)Please set theme of AdActivity to @android:style/Theme.Translucent to enable transparent background interstitial ad.
07-02 20:40:22.680 E/cutils-trace(17167)Error opening trace file: No such file or directory (2)
07-02 20:40:22.680 I/dex2oat (17167)/system/bin/dex2oat --runtime-arg -classpath --runtime-arg  --instruction-set=arm --instruction-set-features=div --runtime-arg -Xrelocate --boot-image=/system/framework/boot.art --dex-file=/data/data/com.electricsheep.asi/cache/ads-2056680341.jar --oat-fd=19 --oat-location=/data/data/com.electricsheep.asi/cache/ads-2056680341.dex --runtime-arg -Xms64m --runtime-arg -Xmx512m
07-02 20:40:22.795 I/dex2oat (17167)dex2oat took 110.913ms (threads: 4) arena alloc=176KB java alloc=12KB native alloc=1155KB free=16KB
07-02 20:40:24.024 I/Choreographer(17099)Skipped 82 frames!  The application may be doing too much work on its main thread.
07-02 20:40:24.893 W/art     (17099)Long monitor contention event with owner method=void java.lang.Object.wait!(long, int) from Object.java:4294967294 waiters=0 for 750ms
07-02 20:40:25.629 I/Timeline(17099)Timeline: Activity_idle id: android.os.BinderProxy@1acab5ed time:3148748
07-02 20:40:26.903 W/chromium(17099)[WARNING:data_reduction_proxy_settings.cc(331)] SPDY proxy OFF at startup
07-02 20:40:26.913 W/art     (17099)Attempt to remove local handle scope entry from IRT, ignoring
07-02 20:40:26.916 W/AwContents(17099)onDetachedFromWindow called when already detached. Ignoring
07-02 20:40:26.929 W/art     (17099)Attempt to remove local handle scope entry from IRT, ignoring
07-02 20:40:26.962 I/Ads     (17099)Trying mediation network: https://googleads.g.doubleclick.net/aclk?sa=L&ai=CRDVlm4WVVbCWIOnY7Qb9oLq4DvnJ2qYF0e-FupIBABAIII-o_iBg1fXSAqkCAAAAAICELkGoAwGqBCBP0FqqnGGCTk9iZC2oxQ3vdYGE7jNEAYRrHOUboH_Yd8AGC4AHgfipMJgHAQ&num=1&cid=5GgOOg&sig=AOD64_1S7Mh7ZgOOia5swwTnX5ljEAhAIA&adurl=http://example.com
07-02 20:40:26.964 I/Ads     (17099)Instantiating mediation adapter: com.google.ads.mediation.inmobi.InMobiAdapter
07-02 20:40:26.969 W/Ads     (17099)Could not instantiate mediation adapter: com.google.ads.mediation.inmobi.InMobiAdapter. com.google.ads.mediation.inmobi.InMobiAdapter
07-02 20:40:26.971 I/Ads     (17099)Trying mediation network:
07-02 20:40:26.971 I/Ads     (17099)Instantiating mediation adapter: com.google.ads.mediation.admob.AdMobAdapter
07-02 20:40:26.971 W/Ads     (17099)Could not instantiate mediation adapter: com.google.ads.mediation.admob.AdMobAdapter. com.google.ads.mediation.admob.AdMobAdapter
07-02 20:40:26.975 I/Ads     (17099)No fill from any mediation ad networks.
07-02 20:40:26.979 I/Ads     (17099)Scheduling ad refresh 40000 milliseconds from now.
07-02 20:40:26.979 W/Ads     (17099)Failed to load ad: 3
07-02 20:40:36.881 D/AndroidSystemInfo(17099)unregisterReceiver( mBattReceiver );
07-02 20:40:36.926 W/art     (17099)Attempt to remove local handle scope entry from IRT, ignoring
07-02 20:40:36.927 W/AwContents(17099)onDetachedFromWindow called when already detached. Ignoring
07-02 20:40:37.008 W/System.err(17099)java.io.FileNotFoundException: /sys/module/lowmemorykiller/parameters/minfree: open failed: EACCES (Permission denied)
07-02 20:40:37.008 W/System.err(17099)at libcore.io.IoBridge.open(IoBridge.java:456)
07-02 20:40:37.008 W/System.err(17099)at java.io.FileInputStream.<init>(FileInputStream.java:76)
07-02 20:40:37.008 W/System.err(17099)at java.io.FileInputStream.<init>(FileInputStream.java:103)
07-02 20:40:37.008 W/System.err(17099)at java.io.FileReader.<init>(FileReader.java:66)
07-02 20:40:37.008 W/System.err(17099)at com.electricsheep.asi.SystInfos.h(Unknown Source)
07-02 20:40:37.008 W/System.err(17099)at com.electricsheep.asi.SystInfos.a(Unknown Source)
07-02 20:40:37.008 W/System.err(17099)at com.electricsheep.asi.bs.run(Unknown Source)
07-02 20:40:37.008 W/System.err(17099)at java.lang.Thread.run(Thread.java:818)
07-02 20:40:37.009 W/System.err(17099)Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
07-02 20:40:37.009 W/System.err(17099)at libcore.io.Posix.open(Native Method)
07-02 20:40:37.009 W/System.err(17099)at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
07-02 20:40:37.009 W/System.err(17099)at libcore.io.IoBridge.open(IoBridge.java:442)
07-02 20:40:37.009 W/System.err(17099)... 7 more
07-02 20:40:37.142 W/System.err(17099)java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
07-02 20:40:37.142 W/System.err(17099)at com.electricsheep.asi.SystInfos.h(Unknown Source)
07-02 20:40:37.142 W/System.err(17099)at com.electricsheep.asi.SystInfos.a(Unknown Source)
07-02 20:40:37.142 W/System.err(17099)at com.electricsheep.asi.bs.run(Unknown Source)
07-02 20:40:37.142 W/System.err(17099)at java.lang.Thread.run(Thread.java:818)

**Comment by AlvaroRosado** [comment]
If you need other log.  Please tell me i will put other.

**Comment by zeroblade1984** [comment]
Not a Logcat..post a last_kmsg..if you can't provide the proper log next time also on how to reproduce the issue then I will close this.. -_-

**Comment by AlvaroRosado** [comment]
Here you have all the logs include last kernel log that i have knowed take.
The issue happend when i try to loggin with google account in any app or game.

For example: 
1. I want to register in (8 ball poll or any app, i have tested other games ands apps, the issue is equal)that which allows register or log in with my Google Account.
2. I logging.
3. the app is loading and force closure occurs

With kernel stock work fine.

-Dowload logs

https://mega.nz/#!xssRDLbQ!u19SflBzPa4ZIHPDCLUYYBfz6BIFgqUapLXptzmeB-8

I have not experienced in discovering incidents android and get the logs.
Please if after this comment, do not manage to understand please close the issue, my sincere apology, my English is not good and I can not explain it better.

A greeting

**Comment by zeroblade1984** [comment]
Thank you rest assured we'll look into this for next update..as we now know how to replicate the issue..

**Comment by adewisman** [comment]
Works fine on me, @krachenko try to use the gapps that recomended by armani-devs and flash the gapps back, what gapps do you use btw?

**Comment by AlvaroRosado** [comment]
Thank you for your work @zeroblade1984 
@adewisman, hi men i have used this gapps 5.1. 
http://forum.xda-developers.com/android/software/gapps-google-apps-minimal-edition-t2943330
I follow these steps:
1.Full wipe.
2.Install rom.
3.Install gapps.
4. wipe dalvik cache and cache.
5. install kernel

R11 the issue happend. R9 work fine and stock kernel too work fine.
