### ISSUE TITLE
Can't Underclock My CPU

### ISSUE THREAD

**Issue by AkhilTMohan** [zeroblade1984/armani_kernel#5]
I am using redmi 1s-MIUI 

I cant underclock my cpu by synapse. I am using miuiv7 with xelerate kernel new buil. 21 august
Your wifes birthday spl... ;)
Kindly help me to underclock it.. Xelerate is a verry good kernel that is available for redmi 1s now.
Good sound. 
Buggless. 
SmoBugglessoth.. Hats off for  your work..!
![screenshot_2015-08-28-19-17-56_1440769807903](https://cloud.githubusercontent.com/assets/14016536/9547721/db95a726-4db9-11e5-9d11-dcdf08217c26.jpg)

**Comment by zeroblade1984** [comment]
do you guys ever read any posts on xda or something?

**Comment by AkhilTMohan** [comment]
sorry i cant get you.. ? :P
Xda which thread?

**Comment by zeroblade1984** [comment]
update busybox..it should stick..also try to use the latest Synapse APK from playstore..@AkhiiTMohan
