### ISSUE TITLE
Restarting when trying to make a call 

### ISSUE THREAD

**Issue by devb23** [zeroblade1984/armani_kernel#7]
I am using Mokee 5.1.1 rom on Xiaomi HM 1s device. Although all my applications work fine with xcelerate kernel except the dailer. Whenever i want to call someone either it hangs or it restarts.

**Comment by zeroblade1984** [comment]
you either wait for the new release or we stop trying to bring an update..I'm getting retarded each day when I look into issues when its clearly stated you HAVE TO WAIT FOR THE UPDATE TO BE RELEASED!!
