### ISSUE TITLE
Xelerate For CM13 (REDMI 1S)

### ISSUE THREAD

**Issue by AkhilTMohan** [zeroblade1984/armani_kernel#8]
Please make the Xelerate kernel working for Cm13 For REDMI 1S

**Comment by naveendabas046** [comment]
Where is link for latest xcelerate kernel (build 23) please add that link too ASAP. thanks in advance

**Comment by zeroblade1984** [comment]
WTF are you doing?

I do this for FREE and at my FREE TIME..nobody dictates what/when/where do I do stuff around here..else lets call it quits...

One more stupid post like this..
